FROM ubuntu:18.04

RUN apt-get update
RUN apt-get -y install git build-essential curl cmake libx11-dev libglu1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev zlib1g-dev libasound2-dev libgtk2.0-dev libjack-jackd2-dev wget unzip vim jq pkg-config libfontconfig1-dev libxft-dev libcairo2-dev libjpeg-dev liblo-dev libsndfile1-dev dssi-dev liblrdf0-dev libsigc++-2.0-dev mesa-common-dev lv2-dev libfftw3-dev liblscp-dev libqt5x11extras5-dev libmad0-dev libsamplerate0-dev librubberband-dev lvtk-dev liblilv-dev libsuil-dev pyqt5-dev-tools qt5-qmake qt5-default liblo-dev libgig-dev libfluidsynth-dev ladspa-sdk subversion g++ debhelper automake libtool fakeroot doxygen uuid-dev bison flex libsqlite3-dev
